name: travel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  go_router: ^3.0.1
  flutter_svg: ^1.0.2
  page_view_indicators: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-Regular.ttf
          weight: 400
        - asset: assets/fonts/Signika-Bold.ttf
          weight: 900
    